In [4]:
import numpy as np

In [8]:
# Broadcasting with Arrays of Different Shapes

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([60, 70, 80, 90, 100])
result = arr1 + arr2
print(result)

[ 70  90 110 130 150]


In [16]:
# Broadcasting: Scaling Arrays Without Extra Memory

arr = np.array([1, 2, 3, 4, 5])
result = arr + 10  # Broadcasting: 10 is added to all elements
print(result)  # Output: [11 12 13 14 15]

[11 12 13 14 15]


In [18]:
# Broadcasting a 2D Array and a 1D Array

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)

[[2 4 6]
 [5 7 9]]


In [22]:
# Hands-on: Applying Broadcasting to Real-World Scenarios:-

# Let’s apply broadcasting to a real-world scenario: scaling data in machine learning.

# Normalizing Data Using Broadcasting:-
# Imagine you have a dataset where each row represents a sample and each column represents a feature. 
# You can normalize the data by subtracting the mean of each column and dividing by the standard deviation.

# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [20]:
# How Broadcasting Works:-

# Dimensions must be compatible: The size of the trailing dimensions of the arrays must be either the same or one of them must be 1.
# Stretching arrays: If the shapes are compatible, NumPy stretches the smaller array to match the larger one, element-wise, without copying data.