In [1]:
# ! pip install library_name                     --> USED TO INSTALL ANY MODE OR LIBRARY IN JUPYTER.

In [3]:
import numpy as np

In [7]:
arr1 = np.array([1, 2, 3, 4, 5])            # 1-D ARRAY
arr2 = np.array([[1, 2, 3], [4, 5, 6]])     # 2-D ARRAy

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [11]:
np.zeros((3, 4))                           # USED TO GENERATE ARRAY OF 0s.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2, 3))                            # USED TO GENERATE ARRAY OF 0s.

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.full((3, 4), 1)                       # USED TO GENERATE ARRAY OF ANY CHARACTER.

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
np.eye(5)                                # USED TO GENERATE 'identity matrix'.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.arange(1, 100, 9)                    # USED TO CREATE AN ARRAY FROM 1 - (N-1), WITH THE GAP IN BETWEEN(3RD ARG.)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [25]:
np.linspace(1, 100, 5)                  # USED TO CREATE AN ARRAY FROM 1 - (N-1), EVENLY SPACED

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [29]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
arr.shape

(4, 3)

In [33]:
arr.size

12

In [35]:
arr.ndim

2

In [37]:
arr.dtype

dtype('int32')

In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=float)  # 'dtype' CAN ALSO BE USED LIKE THIS.

In [41]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [47]:
arr.reshape(2, 6)                  # FOR CHANGING THE SHAPE OF AN ARRAY.

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]])

In [49]:
arr.flatten()                      # CONVERTS ANY ARRAY IN 1-D ARRAY. 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])