In [1]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
flat_arr = arr.flatten()

In [12]:
flat_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
flat_arr[0]

1

In [16]:
flat_arr[2:6]

array([3, 4, 5, 6])

In [18]:
b = flat_arr[4:7]  # Without .copy() --> If you assign one array to another, 
                   # NumPy doesn’t duplicate the data. Both variables point to the same memory location.

In [20]:
b

array([5, 6, 7])

In [22]:
b[1] = 90

In [24]:
b

array([ 5, 90,  7])

In [30]:
b = flat_arr[3:7].copy()    # With .copy() --> If you use .copy(), a new independent array is created.

In [32]:
b

array([ 4,  5, 90,  7])

In [36]:
# FANCY INDEXING (i.e. SELECTING MULTIPLE ELEMENTS IN ARRAY)

b = [0, 2, 4]
print(b)

[0, 2, 4]


In [44]:
mask = flat_arr < 5              # BOOLEAN MASKING

In [46]:
flat_arr[mask]

array([1, 2, 3, 4])