In [1]:
import numpy as np

In [51]:
arr = np.random.rand(3, 3)
print(arr)

[[0.80923419 0.54789306 0.5875958 ]
 [0.01336393 0.30948793 0.95015069]
 [0.35301231 0.491723   0.17970814]]


In [53]:
arr2 = np.random.randint(0, 10, size=(3, 3))

In [55]:
arr2

array([[5, 9, 5],
       [3, 9, 6],
       [7, 4, 5]])

In [67]:
arr.shape
arr2.shape

(3, 3)

In [77]:
arr3 = np.array([1.1, 2.2, 3.3])
arr4 = arr3.astype(int)

In [79]:
arr4

array([1, 2, 3])

In [92]:
arr5 = np.array([1, 2, 3, 4, 5, 6])
fancy_arr5 = arr5[arr5 % 2 == 0]
print(fancy_arr5)   

[2 4 6]


In [94]:
fancy_arr5

array([2, 4, 6])

In [110]:
# create arr6 (must have 9 elements if you want reshape(3,3))
arr6 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# now reshape works
arr6_new = arr6.reshape(3, 3)
print(arr6_new)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [112]:
# BOOLEAN MASKING

arr7 = np.array([10, 55, 60, 30, 45, 100])

# Boolean mask for numbers > 50
mask = arr7 > 50
print("Mask:", mask)      # [False False False  True  True False  True]

# Apply mask to filter
result = arr7[mask]
print("Numbers > 50:", result)

Mask: [False  True  True False False  True]
Numbers > 50: [ 55  60 100]
