In [1]:
import numpy as np

In [5]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [13]:
np.sum(arr)                        # SUM OF ALL ELEMENTS. 

45

In [9]:
np.sum(arr, axis=0)                # VERTICALLY SUM OF ELEMENTS.

array([12, 15, 18])

In [11]:
np.sum(arr, axis=1)                # HORIZONTALLY SUM OF ELEMENTS.

array([ 6, 15, 24])

In [15]:
arr[0,0]                           # FOR ACCESSING ELEMENTS.

1

In [17]:
# OR

arr[0][1]

2

In [19]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [21]:
# Indexing in 3D Arrays

arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape) # Output: (2    , 2   , 3) 

(2, 2, 3)


In [23]:
# Accessing elements in 3D:

# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


In [35]:
# Practical Example: Selecting Data Along Axes

# Get all rows of the first column
first_col = arr[:, 0]
print(first_col, "\n")  # Output: [1 4 7]

# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[1 4 7] 

[[1 2 3]
 [7 8 9]]


In [37]:
# Changing Data Along an Axis

# Replace all elements in column 1 with 0

arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
