In [1]:
import numpy as np

In [3]:
arr = np.array([10, 20, 30, 40])
np.mean(arr)

25.0

In [5]:
np.min(arr)

10

In [8]:
np.max(arr)

40

In [10]:
np.std(arr)  # STANDARD DEVIATION

11.180339887498949

In [12]:
np.var(arr)                         # FOR VARIANCE

125.0

In [14]:
np.sum(arr)

100

In [16]:
np.prod(arr)                        # FOR PRODUCT

240000

In [18]:
np.median(arr)

25.0

In [20]:
np.percentile(arr, 50)  # For the 50th percentile (median)

25.0

In [22]:
np.argmin(arr)                # Return the index of the minimum value in an array.

0

In [24]:
np.argmax(arr)                # Return the index of the maximum value in an array.

3

In [30]:
arr1 = np.array([11, 12, 13, 14])
arr2 = np.array([1, 2, 3, 4])
np.corrcoef(arr1, arr2)       # np.corrcoef(arr1, arr2)

array([[1., 1.],
       [1., 1.]])

In [32]:
np.unique(arr)                # Find the unique elements of an array.

array([10, 20, 30, 40])

In [ ]:
# np.diff() – Compute the n-th differences of an array.

np.diff(arr)

In [ ]:
# np.cumsum() – Compute the cumulative sum of an array.

np.cumsum(arr)

In [34]:
# np.linspace() – Create an array with evenly spaced numbers over a specified interval.

np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
# np.log() – Compute the natural logarithm of an array.

np.log(arr)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945])

In [38]:
# np.exp() – Compute the exponential of an array.

np.exp(arr)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17])